### ISSUE TITLE
e.displayText() = DB::Exception: Access denied to database default for user dataout_user 

### ISSUE THREAD

**Issue by zhougit86** [jaykelin/clickhouse-hdfs-loader#10]
在导数据的时候指定了一个库xxx,但是执行时出现报错
Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 291, host: 10.68.200.228, port: 8123; Code: 291, e.displayText() = DB::Exception: Access denied to database default for user dataout_user (versi
on 19.17.3.7 (official build))

        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:680)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:512)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:105)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:89)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:85)
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:86)

很奇怪为何这个select timezone()会去访问到default库，登陆到数据库上执行select timezone()也没有问题，有大佬指点下吗？

**Comment by jaykelin** [comment]
发一下完整的执行脚本
