### ISSUE TITLE
代码报错问题

### ISSUE THREAD

**Issue by matribots** [jaykelin/clickhouse-hdfs-loader#2]
AbstractClickhouseLoaderMapper.java文件中的这段代码里的hashString报错，提示说是少了个参数，请问该如何解决？
`if(StringUtils.isNotBlank(clickhouseDistributedTableShardingKeyValue)){
                code = hashFn.hashString(clickhouseDistributedTableShardingKeyValue).asInt() & Integer.MAX_VALUE;
            }else{
                code = hashFn.hashString(UUID.randomUUID().toString()).asInt() & Integer.MAX_VALUE;
            }`

**Comment by jaykelin** [comment]
--table 指定是Distributed table吗？以及其建表脚本是怎样的？

**Comment by caolijun1166** [comment]
我还没有用命令行。我是在IDEA上编译源码的时候遇到该报错问题的，是源码里少参数了。

**Comment by jaykelin** [comment]
跳过test试试

**Comment by caolijun1166** [comment]
f

**Comment by caolijun1166** [comment]
代码编译错误已解决。请问打包可执行jar包时，main class应该指定为哪一个（ClickhouseClientHolder、ClickhouseHdfsLoader中都有main方法）。

**Comment by jaykelin** [comment]
ClickhouseHdfsLoader

**Comment by caolijun1166** [comment]
好的，谢谢，我试一下。

**Comment by jaykelin** [comment]
可以参考一下样例：
```shell
hadoop jar $BIPROG_ROOT/bin/java/lib/clickhouse-hdfs-loader.jar com.kugou.loader.clickhouse.ClickhouseHdfsLoader \
-Dmapreduce.job.queuename=root.default \
-i text \
--connect jdbc:clickhouse://xxx:8123/database \
--username xx --password xx \
--table distributed_table \
--dt 2018-01-01 \
--export-dir hdfs_path  \
--extract-hive-partitions true \
--exclude-fields 0,4,5,8 \
--daily false 
```

**Comment by caolijun1166** [comment]
放到hadoop上跑了一下，Map任务显示的是100%，Reduce任务显示的是0%，最后报如下错误，ERROR clickhouse.ClickhouseHdfsLoader: Clickhouse Loader: ERROR! Failed records = 326663，这是什么情况..

**Comment by jaykelin** [comment]
分析map task的日志

**Comment by FangLietao** [comment]
mvn 打包后执行，报错
Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by jaykelin** [comment]
@FangLietao 应该是漏掉了args4j的包
```xml
        <dependency>
            <groupId>args4j</groupId>
            <artifactId>args4j</artifactId>
            <version>2.33</version>
        </dependency>
```

**Comment by jaykelin** [comment]
@FangLietao 执行时是使用 -with-dependencies.jar 这个jar包吗？

**Comment by FangLietao** [comment]
对，有使用那个jar包

**Comment by FangLietao** [comment]
能具体聊一下吗，wechat: za921001
