### ISSUE TITLE
JDBC java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by HadoopChen** [jaykelin/clickhouse-hdfs-loader#3]
## 命令
hadoop_lt jar clickhouse-hdfs-loader-2.0.3-jar-with-dependencies.jar com.kugou.loader.clickhouse.ClickhouseHdfsLoader \
-Dmapreduce.job.queuename=root.cj.default \
-i orc \
--connect jdbc:clickhouse:/1.2.3.4:8123/default \
--table distributed_tag \
--dt 2018-06-23 \
--export-dir /user/cj/hive_db/cj.db/tag2

## 错误

18/06/23 17:47:19 INFO clickhouse.ClickhouseClientHolder: Clickhouse Loader : get clickhouse client[jdbc:clickhouse://1.2.3.4:8123/default] for user=null
18/06/23 17:47:19 INFO clickhouse.ClickHouseDriver: Driver registered
18/06/23 17:47:19 INFO clickhouse.ClickHouseDriver: Creating connection
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:82)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:95)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:104)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:62)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:572)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:174)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.getConnectionManager(ClickHouseHttpClientBuilder.java:77)
	at ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.buildClient(ClickHouseHttpClientBuilder.java:54)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:71)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:50)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:32)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at com.kugou.loader.clickhouse.ClickhouseClient.<init>(ClickhouseClient.java:47)
	at com.kugou.loader.clickhouse.ClickhouseClient.<init>(ClickhouseClient.java:39)
	at com.kugou.loader.clickhouse.ClickhouseClientHolder.getClickhouseClient(ClickhouseClientHolder.java:49)
	at com.kugou.loader.clickhouse.ClickhouseClientHolder.getClickhouseClient(ClickhouseClientHolder.java:57)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.initClickhouseParameters(ClickhouseHdfsLoader.java:223)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.run(ClickhouseHdfsLoader.java:121)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.main(ClickhouseHdfsLoader.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

## 排查

telnet 1.2.3.4 8123    ==>  OK 
default数据库存在、分布式表distributed_tag也存在；
clickhouseServer正常，无报错日志；

## 求助！！！

**Comment by jaykelin** [comment]
缺少参数：--username xxx --password xxx

**Comment by HadoopChen** [comment]
嗯嗯   之前怀疑这个问题，但CH的配置文件里面没有设定账号密码，所以就没加。  请问如何设定CH的JDBC账号密码。

**Comment by HadoopChen** [comment]
哦哦  感谢！

**Comment by HadoopChen** [comment]
## 貌似依然不行

CH本机可以通过clickhouse-client --user default --password default登入CH；但使用JDBC依然不行；报同样的错；均是默认配置，只是给default用户加了一个明文的密码。
 <default>
<password>default</password>
<networks incl="networks" replace="replace">
                <ip>::/0</ip>
</networks>
<profile>default</profile>
<quota>default</quota>
 </default>

## 命令
hadoop_lt jar clickhouse-hdfs-loader-2.0.3-jar-with-dependencies.jar com.kugou.loader.clickhouse.ClickhouseHdfsLoader 
-Dmapreduce.job.queuename=root.cj.default 
-i orc 
--connect jdbc:clickhouse:/1.2.3.4:8123/default 
--username default --password default
--table distributed_tag 
--dt 2018-06-23 
--export-dir /user/cj/hive_db/cj.db/tag2

## 错误
18/06/26 10:35:06 INFO clickhouse.ClickhouseClientHolder: Clickhouse Loader : get clickhouse client[jdbc:clickhouse://nbot113.dg.163.org:8123/default] for user=default
18/06/26 10:35:06 INFO clickhouse.ClickHouseDriver: Driver registered
18/06/26 10:35:06 INFO clickhouse.ClickHouseDriver: Creating connection
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:82)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:95)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:104)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:62)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:572)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:174)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.getConnectionManager(ClickHouseHttpClientBuilder.java:77)
	at ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.buildClient(ClickHouseHttpClientBuilder.java:54)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:71)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:50)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:32)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.kugou.loader.clickhouse.ClickhouseClient.<init>(ClickhouseClient.java:45)
	at com.kugou.loader.clickhouse.ClickhouseClientHolder.getClickhouseClient(ClickhouseClientHolder.java:65)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.initClickhouseParameters(ClickhouseHdfsLoader.java:223)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.run(ClickhouseHdfsLoader.java:121)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at com.kugou.loader.clickhouse.ClickhouseHdfsLoader.main(ClickhouseHdfsLoader.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by jaykelin** [comment]
@HadoopChen http客户端的jar包是不是有冲突

**Comment by HadoopChen** [comment]
![image](https://user-images.githubusercontent.com/19277079/41891689-0f184bd2-7948-11e8-9371-2da861750292.png)

+  CH依赖于httpclient 4.5.2，httpcore 4.5.2
+  hadoop集群2.5.2之后hadoop-common就依赖于httpcore+httpclient 4.5.5，集群环境的jar包无法更换；
+  CH JDBC里面用的HttpClientConnectionManager是属于4.5.2的，如果用provided，则提示不存在该类；如果去掉provided，用4.5.2的版本，又和集群的4.5.5冲突。


咋搞，把jdbc用4.5.5改一遍。旧的类都替换掉 ？

**Comment by jaykelin** [comment]
试试用这个jdbc客户端
https://github.com/jaykelin/clickhouse-jdbc/tree/0.1-SNAPSHOT

**Comment by panda403** [comment]
username 和password是clickhouse的用户名密码吗？我默认单机装的没有用户名密码怎么弄

**Comment by slimtom95** [comment]
use shade relocation to solve this conflicts [ref to](https://stackoverflow.com/a/33331557)
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <relocations>
                    <relocation>
                        <pattern>org.apache.http</pattern>
                        <shadedPattern>shaded.org.apache.http</shadedPattern>
                    </relocation>
                </relocations>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by Balro** [comment]
将冲突包设置为compile，提交作业前设置变量调整hadoop类路径加载顺序，后提交作业。
export HADOOP_CLASSPATH=xxx.jar
export HADOOP_USER_CLASSPATH_FIRST=true
